inference:
  normalize: true
  num_slices: 64
  threshold: 0.3544653356075287
  window:
  - -1000
  - 400
logging:
  level: INFO
model:
  checkpoint_path: weights/best_model.pth
  num_classes: 2
project:
  name: Service4CT
training:
  batch_size: 32
  class_weights: true
  confidence_level: 0.95
  data_file: training_data.csv
  dropout_rate: 0.3
  early_stopping_patience: 20
  epochs: 30
  focal_loss_alpha: 0.75
  focal_loss_gamma: 2.0
  lr: 1e-4
  n_bootstrap: 1000
  optimize_threshold: true
  random_state: 42
  series_dir: data/training_data
  test_size: 0.2
  use_weighted_sampler: true
  val_size: 0.2
  weight_decay: 1e-4
